// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	model "github.com/Mas4trt/microservices/inventory/internal/model"
)

// InventoryRepository is an autogenerated mock type for the InventoryRepository type
type InventoryRepository struct {
	mock.Mock
}

type InventoryRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *InventoryRepository) EXPECT() *InventoryRepository_Expecter {
	return &InventoryRepository_Expecter{mock: &_m.Mock}
}

// Get provides a mock function with given fields: ctx, partUUID
func (_m *InventoryRepository) Get(ctx context.Context, partUUID string) (model.Part, error) {
	ret := _m.Called(ctx, partUUID)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 model.Part
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (model.Part, error)); ok {
		return rf(ctx, partUUID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) model.Part); ok {
		r0 = rf(ctx, partUUID)
	} else {
		r0 = ret.Get(0).(model.Part)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, partUUID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// InventoryRepository_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type InventoryRepository_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - partUUID string
func (_e *InventoryRepository_Expecter) Get(ctx interface{}, partUUID interface{}) *InventoryRepository_Get_Call {
	return &InventoryRepository_Get_Call{Call: _e.mock.On("Get", ctx, partUUID)}
}

func (_c *InventoryRepository_Get_Call) Run(run func(ctx context.Context, partUUID string)) *InventoryRepository_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *InventoryRepository_Get_Call) Return(_a0 model.Part, _a1 error) *InventoryRepository_Get_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *InventoryRepository_Get_Call) RunAndReturn(run func(context.Context, string) (model.Part, error)) *InventoryRepository_Get_Call {
	_c.Call.Return(run)
	return _c
}

// Init provides a mock function with given fields: ctx, parts
func (_m *InventoryRepository) Init(ctx context.Context, parts map[string]model.Part) error {
	ret := _m.Called(ctx, parts)

	if len(ret) == 0 {
		panic("no return value specified for Init")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, map[string]model.Part) error); ok {
		r0 = rf(ctx, parts)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// InventoryRepository_Init_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Init'
type InventoryRepository_Init_Call struct {
	*mock.Call
}

// Init is a helper method to define mock.On call
//   - ctx context.Context
//   - parts map[string]model.Part
func (_e *InventoryRepository_Expecter) Init(ctx interface{}, parts interface{}) *InventoryRepository_Init_Call {
	return &InventoryRepository_Init_Call{Call: _e.mock.On("Init", ctx, parts)}
}

func (_c *InventoryRepository_Init_Call) Run(run func(ctx context.Context, parts map[string]model.Part)) *InventoryRepository_Init_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(map[string]model.Part))
	})
	return _c
}

func (_c *InventoryRepository_Init_Call) Return(_a0 error) *InventoryRepository_Init_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *InventoryRepository_Init_Call) RunAndReturn(run func(context.Context, map[string]model.Part) error) *InventoryRepository_Init_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function with given fields: ctx, filter
func (_m *InventoryRepository) List(ctx context.Context, filter model.PartsFilter) ([]model.Part, error) {
	ret := _m.Called(ctx, filter)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []model.Part
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, model.PartsFilter) ([]model.Part, error)); ok {
		return rf(ctx, filter)
	}
	if rf, ok := ret.Get(0).(func(context.Context, model.PartsFilter) []model.Part); ok {
		r0 = rf(ctx, filter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.Part)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, model.PartsFilter) error); ok {
		r1 = rf(ctx, filter)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// InventoryRepository_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type InventoryRepository_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
//   - filter model.PartsFilter
func (_e *InventoryRepository_Expecter) List(ctx interface{}, filter interface{}) *InventoryRepository_List_Call {
	return &InventoryRepository_List_Call{Call: _e.mock.On("List", ctx, filter)}
}

func (_c *InventoryRepository_List_Call) Run(run func(ctx context.Context, filter model.PartsFilter)) *InventoryRepository_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(model.PartsFilter))
	})
	return _c
}

func (_c *InventoryRepository_List_Call) Return(_a0 []model.Part, _a1 error) *InventoryRepository_List_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *InventoryRepository_List_Call) RunAndReturn(run func(context.Context, model.PartsFilter) ([]model.Part, error)) *InventoryRepository_List_Call {
	_c.Call.Return(run)
	return _c
}

// NewInventoryRepository creates a new instance of InventoryRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewInventoryRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *InventoryRepository {
	mock := &InventoryRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
